### ISSUE TITLE
"Path must be a string.Received undefined"

### ISSUE THREAD

**Issue by js2me** [markerikson/react-redux-cesium-testing-demo#2]
After commands:
`       npm run dll:build`
`       npm run test:build`
`       npm run dev`
I see same problem in ` ./src/index.js `
![image](https://cloud.githubusercontent.com/assets/16340911/22890724/49bfcdbc-f21e-11e6-8407-55482780704a.png)

**Comment by js2me** [comment]
lol.
downgrade node from 6.8.1 to 5.11.1
and all is ok

![image](https://cloud.githubusercontent.com/assets/16340911/22891199/9f25d9da-f21f-11e6-99b3-1124b2b40fc7.png)

**Comment by markerikson** [comment]
Heh.  Yeah, I created this about a year ago, and I was probably running on Node 4 (?) at the time.

I'm hoping to write a blog post soon that discusses how to use Cesium with React and Webpack, and will put together an updated sample repo to go along with the post.

**Comment by valentinmk** [comment]
Hi, same error but i need to run it on nodejs 7. Is there are ideas where to locate this error?
