### ISSUE TITLE
update cesium dependency to 1.30.0

### ISSUE THREAD

**Issue by js2me** [markerikson/react-redux-cesium-testing-demo#3]
I had problem with method :
`new Cesium.HeadingPitchRoll()`
on `"cesium": "^1.18.0"`
to `"cesium": "1.30.0" - 0 errors
If you want I maybe create pull request and watch your repo :3

**Comment by markerikson** [comment]
Not sure it's worth updating this repo at this point.  I actually plan to do a blog post in the next couple weeks talking about how to use Cesium with React and Webpack, and will put together an updated sample repo to go along with it.  Keep an eye on my blog at http://blog.isquaredsoftware.com/ , and I'll probably post some Twitter updates when I'm working on it ( https://twitter.com/acemarke ).

Appreciate the interest, though!
